### ISSUE TITLE
$addToSet alongside a denyUpdate field

### ISSUE THREAD

**Issue by caseylutz** [Meteor-Community-Packages/meteor-collection2#37]
I found an interesting issue today when exploring the use of $addToSet in conjunction with a Collection2 schema. I'll outline what I've done and what I've found.

First, a Collection:

```
@TeamMembers = new SimpleSchema
    memberId: 
        type: String
    accessLevel:
        type: String
        allowedValues: [ 'admin', 'developer', 'watcher' ]
    addedOn:
        type: Date
        autoValue: ->
            if @.isInsert
                new Date

@Teams = new Meteor.Collection2 'teams',
    schema:
        name:
            type: String
            unique: true
        members:
            type: [@TeamMembers]
            optional: true
        createdAt:
            type: Date
            autoValue: ->
                if @.isInsert
                    return new Date
            denyUpdate: true
        updatedAt:
            type: Date
            autoValue: ->
                new Date

```

Of importance here: createdAt is an autoValue for creation date, and it has the denyUpdate property set to true. Members is an array of an object of type TeamMembers. Awesome. 

Now on the server I'm going to insert a team and add a team member to it. Maybe kind of like so (boy I hope I'm doing this right):

```
teamMember = 
    memberId:  userId
    accessLevel:  'admin'
    addedOn:  new Date

Teams.update { _id: team._id }, { $addToSet: { members: teamMember } }
```

This fails SimpleSchema validation. Upon stepping through in node-inspector I found that it was failing on the createdAt key. "That's weird, I didn't even supply a createdAt value..." 

Anyway, in this function:

```
self._simpleSchema.validator(function(key, val, def, op)

key = createdAt
val = undefined
def = denyUpdate, autoValue, label, type
op = $addToSet
```

So the issue appears to be in this block:

```
    if (def.denyUpdate && op !== null) {                                                                       
      // This is an insert of a defined value into a field where denyUpdate=true                               
      if (op === "$set" && val !== void 0) {                                                                   
        return "updateNotAllowed";                                                                             
      } else if (op !== "$set") {                                                                              
        return "updateNotAllowed";     // This is getting hit!                                                                        
      }                                                                                                        
    }                 
```

My assumption here is that the there either needs to be some logic specifically for $addToSet so that it doesn't evaluate the parent object's keys, or there needs to be a check to see if the keyValue is undefined so that SimpleSchema will ignore it. When I removed the denyUpdate field the update went A-OK. 

It may also be worth noting here that I have the updatedAt field which generated an additional $set. This is totally intended in this case.
